const firebaseConfig = {
  apiKey: "AIzaSyBQSGl_cGg_RBqIbIep_cWZMXD_yh8uDSo",
  authDomain: "smart-branch-fd1d8.firebaseapp.com",
  projectId: "smart-branch-fd1d8",
  storageBucket: "smart-branch-fd1d8.firebasestorage.app",
  messagingSenderId: "958934015523",
  appId: "1:958934015523:web:2b0e69e0a65738bb809b96",
  measurementId: "G-DPZ90E14PJ",
};

// Initialize Firebase
firebase.initializeApp(firebaseConfig);
const db = firebase.firestore();

document.getElementById("btn-register").addEventListener("click", async () => {
  // Generate a simple ID based on timestamp (Matching your original logic)
  const autoGeneratedID = "U" + Date.now().toString().slice(-4);

  const userData = {
    Name: document.getElementById("reg-name").value,
    NIC: document.getElementById("reg-nic").value,
    Email: document.getElementById("reg-email").value,
    Password: document.getElementById("reg-pass").value,
    Birthday: document.getElementById("reg-bday").value,
    Town: document.getElementById("reg-town").value,
    User_ID: autoGeneratedID,
  };

  // Simple Validation
  if (Object.values(userData).some((val) => !val)) {
    alert("Please provide all required credentials.");
    return;
  }

  try {
    await db.collection("Users").add(userData);
    alert("Registration Successful! Your User ID is: " + autoGeneratedID);

    // Redirecting back to the customer login index
    window.location.href = "../customerUI/index.html";
  } catch (error) {
    console.error("Error adding user: ", error);
    alert("Connectivity Failed: " + error.message);
  }
});
