// Firebase config (same as your user page)
const firebaseConfig = {
  apiKey: "AIzaSyBQSGl_cGg_RBqIbIep_cWZMXD_yh8uDSo",
  authDomain: "smart-branch-fd1d8.firebaseapp.com",
  projectId: "smart-branch-fd1d8",
  storageBucket: "smart-branch-fd1d8.firebasestorage.app",
  messagingSenderId: "958934015523",
  appId: "1:958934015523:web:2b0e69e0a65738bb809b96",
  measurementId: "G-DPZ90E14PJ",
};

// Initialize Firebase
firebase.initializeApp(firebaseConfig);
const db = firebase.firestore();

document.getElementById("btn-register").addEventListener("click", async () => {
  // Auto generate Staff ID
  const autoGeneratedID = "S" + Date.now().toString().slice(-4);

  const staffData = {
    Name: document.getElementById("staff-name").value,
    Branch_Code: document.getElementById("branch-code").value,
    Staff_ID: autoGeneratedID,
  };

  // Simple validation
  if (!staffData.Name || !staffData.Branch_Code) {
    alert("Please fill all fields");
    return;
  }

  try {
    await db.collection("Staffs").add(staffData);

    alert("Staff Registered Successfully! ID: " + autoGeneratedID);

    window.location.href = "../customerUI/index.html";
  } catch (error) {
    console.error("Error adding staff: ", error);
    alert("Error: " + error.message);
  }
});
