const firebaseConfig = {
  apiKey: "AIzaSyBQSGl_cGg_RBqIbIep_cWZMXD_yh8uDSo",
  authDomain: "smart-branch-fd1d8.firebaseapp.com",
  projectId: "smart-branch-fd1d8",
  storageBucket: "smart-branch-fd1d8.firebasestorage.app",
  messagingSenderId: "958934015523",
  appId: "1:958934015523:web:2b0e69e0a65738bb809b96",
  measurementId: "G-DPZ90E14PJ",
};

firebase.initializeApp(firebaseConfig);
const db = firebase.firestore();

document.getElementById("btn-register").addEventListener("click", async () => {
  // 1. Auto generate Staff ID
  const autoGeneratedID = "S" + Date.now().toString().slice(-4);

  // 2. Capture all data including your new requested fields
  const staffData = {
    Staff_ID: autoGeneratedID,
    Name: document.getElementById("staff-name").value,
    Branch_Code: document.getElementById("branch-code").value.trim(),
    NIC: document.getElementById("staff-nic").value,
    Birthday: document.getElementById("staff-bday").value,
    Email: document.getElementById("staff-email").value,
    Phone: document.getElementById("staff-phone").value,
    Password: document.getElementById("staff-pass").value, // Important for staff login
    Address: document.getElementById("staff-address").value,
  };

  // 3. Validation Check
  if (Object.values(staffData).some((val) => !val)) {
    alert("Institutional Requirement: All fields must be completed.");
    return;
  }

  try {
    // 4. Save to 'Staffs' collection
    await db.collection("Staffs").add(staffData);
    alert("Staff Registered Successfully! Assigned ID: " + autoGeneratedID);

    // 5. Redirect back to login portal
    window.location.href = "../staffReg/index.html";
  } catch (error) {
    console.error("Error onboarding staff: ", error);
    alert("Registration Failed: " + error.message);
  }
});
